data:
  load_file_path: 'synthetic_credit_card_approval.csv'
model:
  save_file_path: 'outputs/selected_model.joblib'
  save_metrics_file_path: 'outputs/selected_model_metrics.joblib'
mlflow:
  experiment_name : 'Harness Example MLOps'
  tracking_uri : 'https://mlflow.sandbox.harness-demo.site'
