FROM public.ecr.aws/lambda/python:3.10

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the specified packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install dependencies for LightGBM
RUN yum update -y && \
    yum install -y gcc gcc-c++ make cmake libgomp
RUN pip install lightgbm
