apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-bank
  labels:
    app: harness-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harness-bank
  template:
    metadata:
      labels:
        app: harness-bank
    spec:
      containers:
        - name: harness-bank
          image: us-east1-docker.pkg.dev/sales-209522/titra/harness-bank:0.0.1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: harness-bank-service
spec:
  selector:
    app: harness-bank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harness-bank-external
spec:
  ingressClassName: nginx
  rules:
  - host: harness-bank.sandbox.harness-demo.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harness-bank-service
            port:
              number: 80
  tls:
  - hosts:
    - harness-bank.sandbox.harness-demo.site
